In [1]:
import math

def basic_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

In [2]:
print(basic_sigmoid(-1))

0.2689414213699951


In [3]:
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [4]:
print(x+3)

[4 5 6]


In [5]:
import numpy as np
def sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s

In [6]:
print(sigmoid(x))

[0.73105858 0.88079708 0.95257413]


In [7]:
def gradient_sigmoid(x):
    gs = sigmoid(x)*(1 - sigmoid(x))
    return gs

In [8]:
print(gradient_sigmoid(x))

[0.19661193 0.10499359 0.04517666]


In [20]:
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return v

In [21]:
image = np.array([[[0.67826139,0.29380381],
                   [0.90714982,0.52835647],
                   [0.4215251,0.45017551]],
                  
                  [[0.92814219,0.96677647],
                   [0.85304703,0.52351845],
                   [0.19981397,0.27417313]],
                  
                  [[0.60659855,0.00533165],
                   [0.10820313,0.49978937],
                   [0.34144279,0.94630077]]])
print(str(image2vector(image)))

[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [23]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x,axis=1, keepdims = True)
    x = x/x_norm
    return x

In [24]:
x = np.array([
    [0,1000,4],
    [2,6,4]])

print(str(normalizeRows(x)))

[[0.         0.999992   0.00399997]
 [0.26726124 0.80178373 0.53452248]]


In [25]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum
    return s

In [26]:
x = np.array([
    [9,2,5,0,0],
    [7,5,0,0,0]])
print(str(softmax(x)))

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [35]:
import time

x1 = np.random.rand(100000)
x2 = np.random.rand(100000)

tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print(str(dot)+"\n"+ str(1000*(toc-tic))+"ms")

24976.162434382924
15.625ms


In [36]:
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print(str(dot)+"\n"+ str(1000*(toc-tic))+"ms")

24976.1624343831
0.0ms
